name: Build and Deploy to GCS

on:
  release:
    types: [created]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Build the hugo website
    - name: Action Hugo
      uses: kevvurs/action-hugo@v1.0-rc2
